package com.tedd.teddreader.core.designsystem

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

val InkIndigo = Color(0xFF4D43B8)
val PaperCream = Color(0xFFFFFBF2)
val BookmarkAmber = Color(0xFFE39A2E)
val SepiaCopper = Color(0xFF8A4D26)
val NightInk = Color(0xFF12100D)
val Sage = Color(0xFF8A9B74)

@Immutable
data class TeddReaderColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
)

val LightTeddReaderColors = TeddReaderColors(
    primary = InkIndigo,
    onPrimary = PaperCream,
    primaryContainer = Color(0xFFE5E0FF),
    onPrimaryContainer = Color(0xFF171055),
    inversePrimary = Color(0xFFC8C0FF),
    secondary = Sage,
    onSecondary = PaperCream,
    secondaryContainer = Color(0xFFDDE4D2),
    onSecondaryContainer = Color(0xFF1E2417),
    tertiary = SepiaCopper,
    onTertiary = PaperCream,
    tertiaryContainer = Color(0xFFFFDBC7),
    onTertiaryContainer = Color(0xFF321200),
    error = Color(0xFFBA1A1A),
    onError = Color.White,
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = PaperCream,
    onBackground = Color(0xFF1D1B16),
    surface = PaperCream,
    onSurface = Color(0xFF1D1B16),
    surfaceVariant = Color(0xFFE9E1D4),
    onSurfaceVariant = Color(0xFF4A463D),
    surfaceDim = Color(0xFFE1D8CA),
    surfaceBright = PaperCream,
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFFCF4E8),
    surfaceContainer = Color(0xFFF7EFE3),
    surfaceContainerHigh = Color(0xFFF1E9DD),
    surfaceContainerHighest = Color(0xFFECE3D7),
    inverseSurface = Color(0xFF32302A),
    inverseOnSurface = Color(0xFFF6EFE4),
    outline = Color(0xFF7B776D),
    outlineVariant = Color(0xFFCCC5B8),
    scrim = Color.Black,
)

val DarkTeddReaderColors = TeddReaderColors(
    primary = Color(0xFFC8C0FF),
    onPrimary = Color(0xFF29206F),
    primaryContainer = Color(0xFF4036A0),
    onPrimaryContainer = Color(0xFFE5E0FF),
    inversePrimary = InkIndigo,
    secondary = Color(0xFFD1D8BF),
    onSecondary = Color(0xFF1D2217),
    secondaryContainer = Color(0xFF40493A),
    onSecondaryContainer = Color(0xFFEAF0DF),
    tertiary = BookmarkAmber,
    onTertiary = NightInk,
    tertiaryContainer = Color(0xFF6D370F),
    onTertiaryContainer = Color(0xFFFFE1B6),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = NightInk,
    onBackground = Color(0xFFE9E1D6),
    surface = NightInk,
    onSurface = Color(0xFFE9E1D6),
    surfaceVariant = Color(0xFF4A463D),
    onSurfaceVariant = Color(0xFFCCC5B8),
    surfaceDim = NightInk,
    surfaceBright = Color(0xFF3B3832),
    surfaceContainerLowest = Color(0xFF0F0D0A),
    surfaceContainerLow = Color(0xFF1D1B16),
    surfaceContainer = Color(0xFF211F1A),
    surfaceContainerHigh = Color(0xFF2B2923),
    surfaceContainerHighest = Color(0xFF36332D),
    inverseSurface = Color(0xFFE9E1D6),
    inverseOnSurface = Color(0xFF32302A),
    outline = Color(0xFF969085),
    outlineVariant = Color(0xFF4A463D),
    scrim = Color.Black,
)
