plugins {
    // Without a version: the Android plugin already sits on the build's classpath through build-logic,
    // and asking for it again with a version makes Gradle refuse to resolve it. AGP 9 compiles Kotlin
    // itself, so no separate Kotlin plugin belongs here.
    id("com.android.test")
    alias(libs.plugins.androidxBaselineProfile)
}

// A profile is generated by driving the real app on a device, so this module is an Android test
// project rather than a library: it has no code the app links against and nothing it produces ends up
// in an ordinary build. The app consumes only the generated text file.
android {
    namespace = "com.tedd.teddreader.baselineprofile"
    compileSdk = libs.versions.android.compileSdk.get().toInt()
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    defaultConfig {
        minSdk = 28
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    targetProjectPath = ":androidApp"
}

// Generation needs a rooted emulator or a userdebug device; a locked production device cannot install
// the instrumented runner against a release build.
baselineProfile {
    useConnectedDevices = true
}

dependencies {
    implementation(libs.androidx.test.junit)
    implementation(libs.androidx.uiautomator)
    implementation(libs.androidx.benchmark.macro.junit4)
}
